version: '3.9'

services:
  database_delivery:
    image: postgres
    container_name: database_delivery
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dude
      - POSTGRES_DB=delivery_dude
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: delivery_dude
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_delivery
    depends_on:
      - database_delivery

volumes:
  pgdata:
    driver: local
